### ISSUE TITLE
Preview links are broken

### ISSUE THREAD

**Issue by ibeckermayer** [YunoHost-Apps/mattermost_ynh#341] opened 2022-02-26 02:24 UTC
### Describe the bug

The ability to preview links in the latest version of mattermost/ynh appears broken

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: `4.3.5`
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: `6.3.3~ynh1`

### Steps to reproduce

   1. Send a link to any channel or DM
   2. Note that the link preview doesn't show up

### Expected behavior

There should be a link preview.

Others have noted the same bug [on the yunohost forum](https://forum.yunohost.org/t/preview-links-broken-bug-mattermost/18912)

**Comment by kemenaran** [comment] 2022-02-26 13:11
Thanks for the report! I guess it's a duplicate of #340

**Closed by kemenaran** 2022-02-26 13:11 UTC
